#!/bin/bash

# Fungsi untuk mengirim log ke Telegram
function send_log() {
    CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
    KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
    TIME="10"
    URL="https://api.telegram.org/bot$KEY/sendMessage"
    TEXT="
<code>────────────────────</code>
<b>⚠️ NOTIF QUOTA HABIS ⚠️</b>
<code>────────────────────</code>
<code>Username  : </code><code>$user</code>
<code>Usage     : </code><code>$total</code>
<code>────────────────────</code>
"
    curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
}

# Fungsi untuk mengonversi byte ke format yang lebih mudah dibaca
function convert_bytes() {
    local -i bytes=$1
    if [[ $bytes -lt 1024 ]]; then
        echo "${bytes}B"
    elif [[ $bytes -lt 1048576 ]]; then
        echo "$(( (bytes + 1023) / 1024 ))KB"
    elif [[ $bytes -lt 1073741824 ]]; then
        echo "$(( (bytes + 1048575) / 1048576 ))MB"
    else
        echo "$(( (bytes + 1073741823) / 1073741824 ))GB"
    fi
}

# Fungsi untuk memeriksa quota pengguna VMess
function cek_vmess() {
    local users=($(grep '^###' /etc/xray/config.json | cut -d ' ' -f 2 | sort | uniq))
    mkdir -p /etc/limit/vmess

    for user in "${users[@]}"; do
        mkdir -p /tmp/quota
        local data=$(xray api statsquery --server=127.0.0.1:10000 | grep -C 2 "$user" | sed '/}/d' | sed '/{/d' | grep value | awk '{print $2}' | sed 's/,//g; s/"//g' | sort)
        local inb=$(echo "$data" | sed -n 1p)
        local outb=$(echo "$data" | sed -n 2p)
        local quota_used=$((inb + outb))

        if [[ -e /etc/limit/vmess/$user ]]; then
            local previous_quota=$(cat /etc/limit/vmess/$user)
            if [[ -n $previous_quota ]]; then
                quota_used=$((quota_used + previous_quota))
            fi
        fi

        echo "$quota_used" > /etc/limit/vmess/$user
        xray api stats --server=127.0.0.1:10000 -name "user>>>$user>>>traffic>>>downlink" -reset >/dev/null 2>&1
    done
}

# Fungsi untuk memeriksa quota pengguna VLess
function cek_vless() {
    local users=($(grep '^#&' /etc/xray/config.json | cut -d ' ' -f 2 | sort | uniq))
    mkdir -p /etc/limit/vless

    for user in "${users[@]}"; do
        mkdir -p /tmp/quota
        local data=$(xray api statsquery --server=127.0.0.1:10000 | grep -C 2 "$user" | sed '/}/d' | sed '/{/d' | grep value | awk '{print $2}' | sed 's/,//g; s/"//g' | sort)
        local inb=$(echo "$data" | sed -n 1p)
        local outb=$(echo "$data" | sed -n 2p)
        local quota_used=$((inb + outb))

        if [[ -e /etc/limit/vless/$user ]]; then
            local previous_quota=$(cat /etc/limit/vless/$user)
            if [[ -n $previous_quota ]]; then
                quota_used=$((quota_used + previous_quota))
            fi
        fi

        echo "$quota_used" > /etc/limit/vless/$user
        xray api stats --server=127.0.0.1:10000 -name "user>>>$user>>>traffic>>>downlink" -reset >/dev/null 2>&1
    done
}

# Fungsi untuk memeriksa quota pengguna Trojan
function cek_trojan() {
    local users=($(grep '^#!' /etc/xray/config.json | cut -d ' ' -f 2 | sort | uniq))
    mkdir -p /etc/limit/trojan

    for user in "${users[@]}"; do
        mkdir -p /tmp/quota
        local data=$(xray api statsquery --server=127.0.0.1:10000 | grep -C 2 "$user" | sed '/}/d' | sed '/{/d' | grep value | awk '{print $2}' | sed 's/,//g; s/"//g' | sort)
        local inb=$(echo "$data" | sed -n 1p)
        local outb=$(echo "$data" | sed -n 2p)
        local quota_used=$((inb + outb))

        if [[ -e /etc/limit/trojan/$user ]]; then
            local previous_quota=$(cat /etc/limit/trojan/$user)
            if [[ -n $previous_quota ]]; then
                quota_used=$((quota_used + previous_quota))
            fi
        fi

        echo "$quota_used" > /etc/limit/trojan/$user
        xray api stats --server=127.0.0.1:10000 -name "user>>>$user>>>traffic>>>downlink" -reset >/dev/null 2>&1
    done
}

# Fungsi untuk memantau quota pengguna VMess
function monitor_vmess() {
    while true; do
        sleep 30
        cek_vmess
        local users=($(grep '^###' /etc/xray/config.json | cut -d ' ' -f 2 | sort | uniq))

        for user in "${users[@]}"; do
            if [[ -e /etc/vmess/$user ]]; then
                local limit=$(cat /etc/vmess/$user)
                local usage=$(cat /etc/limit/vmess/$user)

                if [[ $usage -gt $limit ]]; then
                    local exp=$(grep -w "^### $user" /etc/xray/config.json | cut -d ' ' -f 3 | sort | uniq)
                    sed -i "/^### $user $exp/,/^},{/d" /etc/xray/config.json
                    sed -i "/^### $user $exp/d" /etc/vmess/.vmess.db
                    systemctl restart xray >/dev/null 2>&1
                    total=$(convert_bytes $usage)
                    send_log
                    rm -rf /etc/limit/vmess/$user
                fi
            fi
        done
    done
}

# Fungsi untuk memantau quota pengguna VLess
function monitor_vless() {
    while true; do
        sleep 30
        cek_vless
        local users=($(grep '^#&' /etc/xray/config.json | cut -d ' ' -f 2 | sort | uniq))

        for user in "${users[@]}"; do
            if [[ -e /etc/vless/$user ]]; then
                local limit=$(cat /etc/vless/$user)
                local usage=$(cat /etc/limit/vless/$user)

                if [[ $usage -gt $limit ]]; then
                    local exp=$(grep -w "^#& $user" /etc/xray/config.json | cut -d ' ' -f 3 | sort | uniq)
                    sed -i "/^#& $user $exp/,/^},{/d" /etc/xray/config.json
                    sed -i "/^#& $user $exp/d" /etc/vless/.vless.db
                    systemctl restart xray >/dev/null 2>&1
                    total=$(convert_bytes $usage)
                    send_log
                    rm -rf /etc/limit/vless/$user
                fi
            fi
        done
    done
}

# Fungsi untuk memantau quota pengguna Trojan
function monitor_trojan() {
    while true; do
        sleep 30
        cek_trojan
        local users=($(grep '^#!' /etc/xray/config.json | cut -d ' ' -f 2 | sort | uniq))

        for user in "${users[@]}"; do
            if [[ -e /etc/trojan/$user ]]; then
                local limit=$(cat /etc/trojan/$user)
                local usage=$(cat /etc/limit/trojan/$user)

                if [[ $usage -gt $limit ]]; then
                    local exp=$(grep -w "^#! $user" /etc/xray/config.json | cut -d ' ' -f 3 | sort | uniq)
                    sed -i "/^#! $user $exp/,/^},{/d" /etc/xray/config.json
                    sed -i "/^#! $user $exp/d" /etc/trojan/.trojan.db
                    systemctl restart xray >/dev/null 2>&1
                    total=$(convert_bytes $usage)
                    send_log
                    rm -rf /etc/limit/trojan/$user
                fi
            fi
        done
    done
}

# Menjalankan fungsi berdasarkan argumen
case "$1" in
    "vmess")
        monitor_vmess
        ;;
    "vless")
        monitor_vless
        ;;
    "trojan")
        monitor_trojan
        ;;
    *)
        echo "Usage: $0 {vmess|vless|trojan}"
        exit 1
        ;;
esac
