#!/bin/bash
# My Telegram : https://t.me/amgeekzssh
# ==========================================
# Color
GREEN='\e[32m'
RED='\033[0;31m'
BGBLUE='\e[1;44m'
ORANGE='\033[0;33m'
BLUE='\033[1;36m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
BG='\E[44;1;39m'
NC='\033[0;37m'
WHITE='\033[0;37m'
r="\033[1;31m"  #REDTERANG
# ==========================================
# Getting
export CHATID="1210833546"
export KEY="6006599143:AAEgstCAioq35JgX97HaW_G3TAkLKzLZS_w"
export TIME="10"
export URL="https://api.telegram.org/bot$KEY/sendMessage"
clear
#IZIN SCRIPT
MYIP=$(curl -sS ipv4.icanhazip.com)
echo -e "\e[32mloading...\e[0m"
clear
# Valid Script
ipsaya=$(wget -qO- ipinfo.io/ip)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
clear
#Domain
domain=$(cat /etc/xray/domain)

echo -e "$BLUE╭──────────────────────────────────────────╮$NC"
echo -e "$BLUE│$NC$BG                SSH & OpenVPN             $NC$BLUE│$NC"
echo -e "$BLUE╰──────────────────────────────────────────╯$NC"
echo -e "$BLUE╭──────────────────────────────────────────╮$NC"
echo -e "  [${r}01${NC}]$WHITE Create SSH & OpenVPN Account${NC}"
echo -e "  [${r}02${NC}]$WHITE Trial SSH & OpenVPN ${NC}"
echo -e "  [${r}03${NC}]$WHITE Renew SSH & OpenVPN ${NC}"
echo -e "  [${r}04${NC}]$WHITE Check User Login SSH & OpenVPN${NC}"
echo -e "  [${r}05${NC}]$WHITE Daftar Member SSH & OpenVPN ${NC}"
echo -e "  [${r}06${NC}]$WHITE Hapus SSH & OpenVpn Account ${NC}"
echo -e "  [${r}07${NC}]$WHITE Hapus User Expired SSH & OpenVPN ${NC}"
echo -e "  [${r}08${NC}]$WHITE Set up Autokill SSH ${NC}"
echo -e "  [${r}09${NC}]$WHITE Cek User Multi Login SSH ${NC}"
echo -e "  [${r}10${NC}]$WHITE Config SSH ACCOUNT ${NC}"
echo -e "  [${r}00${NC}]$WHITE Back To Menu ${NC}"
echo -e "$BLUE╰──────────────────────────────────────────╯$NC"
read -p "Select From Options [ 1 - 10 ] : " menu
echo -e ""
case $menu in
1 | 01)
    addssh
    ;;
2 | 02)
    trial
    ;;
3 | 03)
    renewssh
    ;;
4 | 04)
    cekssh
    ;;
5 | 05)
    member
    ;;
6 | 06)
    delssh
    ;;
7 | 07)
    delexp
    ;;
8 | 08)
    autokill
    ;;
9 | 09)
    ceklim
    ;;
10)
    user-ssh
    ;;
0 | 00)
menu
;;
*)
    m-sshws
    ;;
esac
