#!/bin/bash
# My Telegram : https://t.me/amgeekzssh
# ==========================================
# Color
GREEN='\e[32m'
RED='\033[0;31m'
BGBLUE='\e[1;44m'
ORANGE='\033[0;33m'
BLUE='\033[1;36m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
BG='\E[44;1;39m'
NC='\033[0;37m'
WHITE='\033[0;37m'
r="\033[1;31m"  #REDTERANG
# ==========================================
# Getting
export CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
export KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
export TIME="10"
export URL="https://api.telegram.org/bot$KEY/sendMessage"
clear
# Getting
ipsaya=$(wget -qO- ipinfo.io/ip)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
clear
echo -e "$BLUE╭──────────────────────────────────────────╮$NC"
echo -e "                 MENU VMESS              $NC"
echo -e "$BLUE╰──────────────────────────────────────────╯$NC"
echo -e "$BLUE╭──────────────────────────────────────────╮$NC"
echo -e "  ${WHITE}1.${NC} \033[0;36m Creating Vmess Account WS/GRPC${NC}"
echo -e "  ${WHITE}2.${NC} \033[0;36m Creating Trial Vmess Account WS/GRPC${NC}"
echo -e "  ${WHITE}3.${NC} \033[0;36m Delete Vmess Account WS/GRPC${NC}"
echo -e "  ${WHITE}4.${NC} \033[0;36m Renew Vmess Account${NC}"
echo -e "  ${WHITE}5.${NC} \033[0;36m Check Vmess login Account${NC}"
echo -e "  ${WHITE}6.${NC} \033[0;36m Check Config Vmess Account${NC}"
echo -e "  ${WHITE}0.${NC} \033[0;36m Back To Menu${NC}"
echo -e "$BLUE╰──────────────────────────────────────────╯$NC"
echo -e ""
read -p "Select From Options [ 1 - 6 ] : " menu
case $menu in
1)   clear ;
    addws
    ;;
2) clear ;
    trialws
    ;;
3) clear ;
    delws
    ;;
4) clear ;
    renewws
    ;;
5) clear ;
    cekws
    ;;
6) clear ;
    user-ws
    ;;
0) clear ;
    menu
    ;;
*) clear ;
    menu
    ;;
esac
